name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release-please:
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - id: release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          release-type: node
          token: ${{ github.token }}

  publish:
    needs: release-please
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ needs.release-please.outputs.should-release == 'true' }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Create .npmrc
        run: |
          (
            # shellcheck disable=SC2016
            echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}'
            echo 'registry=https://registry.npmjs.org'
          ) > .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
